version: "3.7"

services:
  agent.normal.scanner:
    image: node:latest
    container_name: agent.normal.scanner
    build: 
      context: .
      dockerfile: Dockerfile.node
    environment:
      - RPC_IP=${RPC_IP}
      - NODE_ENV=production
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - "../agent:/home/agent"
    command: bash -c "cd /home/agent && node app.js"
    tty: true
    
