version: "3.7"

services:
  db.mongo.scanner:
    image: mongo
    container_name: db.mongo.scanner
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    restart: always
  
  db.redis.scanner:
    image: redis
    container_name: db.redis.scanner
    ports:
      - "6379:6379"